#language: node_js
#node_js:
#    - "6"
#git:
#  submodules: false
#install:
#    - npm install
#    - npm install -g codecov istanbul
#test:
#    - npm run test

#指定运行环境
language: java
jdk:
  - oraclejdk8
install: ./install-dependencies.sh

